version: '3.8'

services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MYSQL_TYPE: ${MYSQL_TYPE}
        MYSQL_VERSION: ${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./backup:/var/lib/mysql
    ports:
      - "3306:3306"
    command: [
      '--server-id=1',
      '--log-bin=mysql-bin'
    ]

  slave:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MYSQL_TYPE: ${MYSQL_TYPE}
        MYSQL_VERSION: ${MYSQL_VERSION}
    container_name: ${CONTAINER_NAME_SLAVE}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    command: [
      '--server-id=2',
      '--relay-log=mysql-relay-bin',
      '--log-slave-updates=1'
    ]
