version: '3.8'

services:
  master:
    build: .
    args:
        - MYSQL_TYPE=${MYSQL_TYPE}
        - MYSQL_VERSION=${MYSQL_VERSION}
    container_name: ${CONTAINER_NAME_MASTER}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./backup:/var/lib/mysql
      - ./config:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    command: [
      '--server-id=1',
      '--log-bin=mysql-bin'
    ]